# This file was generated by GoReleaser. DO NOT EDIT.
cask "bridgectl" do
  name "bridgectl"
  desc "gRPC daemon and SDK that manages AI agent subprocess lifecycles over a PTY transport"
  homepage "https://github.com/orchael/bridgectl"
  version "1.4.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bridgectl"

  on_macos do
    on_intel do
      url "https://github.com/orchael/bridgectl/releases/download/v#{version}/bridgectl_#{version}_darwin_amd64.tar.gz"
      sha256 "01dd1082147afb11585729359b70289456b78982575859ab9e32b8af429a366f"
    end
    on_arm do
      url "https://github.com/orchael/bridgectl/releases/download/v#{version}/bridgectl_#{version}_darwin_arm64.tar.gz"
      sha256 "10cd5a253ffd186c8bed60a710da986ff585ad5a810a31be9ddd5f43257a238d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/orchael/bridgectl/releases/download/v#{version}/bridgectl_#{version}_linux_amd64.tar.gz"
      sha256 "d9ef00ba91683e7d0ef7970501a39c11eef51671886831c485b61fcd509668b1"
    end
    on_arm do
      url "https://github.com/orchael/bridgectl/releases/download/v#{version}/bridgectl_#{version}_linux_arm64.tar.gz"
      sha256 "7b17df107300232c3b63f4650beb0b3bb7f1edfc2fff3b08a834498fa92a1c47"
    end
  end

  caveats do
    "bridgectl runs the provider CLIs (claude, codex, gemini, opencode) through"
    "Node.js 24. Install it separately if you have not already:"
    ""
    "  brew install node@24"
    ""
    "To run the bridge server at login, install the launchd agent:"
    ""
    "  bridgectl server install-agent --start"
    ""
    "The agent is generated from this binary's real path and inherits the PATH"
    "of the shell you run it from, so it finds node and the provider CLIs."
    "Logs go to ~/Library/Logs/bridgectl/. Remove it with:"
    ""
    "  bridgectl server uninstall-agent"
  end

  uninstall launchctl: [
      "com.orchael.bridgectl",
    ]

  zap launchctl: [
      "com.orchael.bridgectl",
    ],
    trash: [
      "~/Library/LaunchAgents/com.orchael.bridgectl.plist",
      "~/Library/Logs/bridgectl",
    ]

end
