# This file was generated by GoReleaser. DO NOT EDIT.
cask "bridgectl" do
  name "bridgectl"
  desc "gRPC daemon and SDK that manages AI agent subprocess lifecycles over a PTY transport"
  homepage "https://github.com/orchael/bridgectl"
  version "1.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bridgectl"

  on_macos do
    on_intel do
      url "https://github.com/orchael/bridgectl/releases/download/v#{version}/bridgectl_#{version}_darwin_amd64.tar.gz"
      sha256 "7c943f449b43bf319cd6a9f3ebe675be8b63e3afd069a25f1649bd49c68fa555"
    end
    on_arm do
      url "https://github.com/orchael/bridgectl/releases/download/v#{version}/bridgectl_#{version}_darwin_arm64.tar.gz"
      sha256 "dda6b99836cb1e18234e50d89339288fe82af9c712d544e9954aa95fa7b475ac"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/orchael/bridgectl/releases/download/v#{version}/bridgectl_#{version}_linux_amd64.tar.gz"
      sha256 "a43f6dce987a4315c8328fca40921651d91c9ada1a1b426de3424404a15f5d37"
    end
    on_arm do
      url "https://github.com/orchael/bridgectl/releases/download/v#{version}/bridgectl_#{version}_linux_arm64.tar.gz"
      sha256 "f3ca49cb74cf9a0ae8c862e6f0a9affa82bf5689bd40b77bf7e9914ff9494dee"
    end
  end

  caveats do
    "bridgectl runs the provider CLIs (claude, codex, gemini, opencode) through"
    "Node.js 24. Install it separately if you have not already:"
    ""
    "  brew install node@24"
    ""
    "To run the daemon at login, see the launchd plist documented in the README."
  end

  # No zap stanza required
end
